---
deployment:
  tasks:
    - export DEPLOYPATH=/home/themgbpn/public_html/karting
    - echo "Deploying to $DEPLOYPATH..."
    - mkdir -p "$DEPLOYPATH"
    - >-
      if command -v rsync >/dev/null 2>&1; then
        rsync -av --delete dashboard/ "$DEPLOYPATH/"
      else
        cp -a dashboard/. "$DEPLOYPATH/"
      fi
    - echo "✅ Deployment complete!"
      - echo "✅ Deployment complete!"
